// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_LBLmain;
lv_obj_t * ui_CTRstatus;
lv_obj_t * ui_LBLbroker;
lv_obj_t * ui_LBLwireless;
lv_obj_t * ui_LBLpublish;
lv_obj_t * ui_LBLtopic;
lv_obj_t * ui_LVLbrokerip;
lv_obj_t * ui_LBLip;
lv_obj_t * ui_CTRdata;
lv_obj_t * ui_LBLpressure;
lv_obj_t * ui_LBLtemp;
lv_obj_t * ui_LBLhumidity;
lv_obj_t * ui_LBLhumVAL;
lv_obj_t * ui_LBLpressVAL;
lv_obj_t * ui_LBLtempVAL;
lv_obj_t * ui_LBLgas;
lv_obj_t * ui_LBLaltitude;
lv_obj_t * ui_LBLgasVAL;
lv_obj_t * ui_LBLaltVAL;
// CUSTOM VARIABLES
lv_obj_t * uic_LBLmain;
lv_obj_t * uic_CTRstatus;
lv_obj_t * uic_LBLbroker;
lv_obj_t * uic_LBLwireless;
lv_obj_t * uic_LBLpublish;
lv_obj_t * uic_LBLtopic;
lv_obj_t * uic_LVLbrokerip;
lv_obj_t * uic_LBLip;
lv_obj_t * uic_CTRdata;
lv_obj_t * uic_LBLpressure;
lv_obj_t * uic_LBLtemp;
lv_obj_t * uic_LBLhumidity;
lv_obj_t * uic_LBLhumVAL;
lv_obj_t * uic_LBLpressVAL;
lv_obj_t * uic_LBLtempVAL;
lv_obj_t * uic_LBLgas;
lv_obj_t * uic_LBLaltitude;
lv_obj_t * uic_LBLgasVAL;
lv_obj_t * uic_LBLaltVAL;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
