// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lib/lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_LBLmain;
extern lv_obj_t * ui_CTRstatus;
extern lv_obj_t * ui_LBLbroker;
extern lv_obj_t * ui_LBLwireless;
extern lv_obj_t * ui_LBLpublish;
extern lv_obj_t * ui_LBLtopic;
extern lv_obj_t * ui_LVLbrokerip;
extern lv_obj_t * ui_LBLip;
extern lv_obj_t * ui_CTRdata;
extern lv_obj_t * ui_LBLpressure;
extern lv_obj_t * ui_LBLtemp;
extern lv_obj_t * ui_LBLhumidity;
extern lv_obj_t * ui_LBLhumVAL;
extern lv_obj_t * ui_LBLpressVAL;
extern lv_obj_t * ui_LBLtempVAL;
extern lv_obj_t * ui_LBLgas;
extern lv_obj_t * ui_LBLaltitude;
extern lv_obj_t * ui_LBLgasVAL;
extern lv_obj_t * ui_LBLaltVAL;
// CUSTOM VARIABLES
extern lv_obj_t * uic_LBLmain;
extern lv_obj_t * uic_CTRstatus;
extern lv_obj_t * uic_LBLbroker;
extern lv_obj_t * uic_LBLwireless;
extern lv_obj_t * uic_LBLpublish;
extern lv_obj_t * uic_LBLtopic;
extern lv_obj_t * uic_LVLbrokerip;
extern lv_obj_t * uic_LBLip;
extern lv_obj_t * uic_CTRdata;
extern lv_obj_t * uic_LBLpressure;
extern lv_obj_t * uic_LBLtemp;
extern lv_obj_t * uic_LBLhumidity;
extern lv_obj_t * uic_LBLhumVAL;
extern lv_obj_t * uic_LBLpressVAL;
extern lv_obj_t * uic_LBLtempVAL;
extern lv_obj_t * uic_LBLgas;
extern lv_obj_t * uic_LBLaltitude;
extern lv_obj_t * uic_LBLgasVAL;
extern lv_obj_t * uic_LBLaltVAL;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
