// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LBLmain = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LBLmain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LBLmain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LBLmain, 1);
    lv_obj_set_y(ui_LBLmain, -95);
    lv_obj_set_align(ui_LBLmain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LBLmain, "Environmental Sensor");
    lv_obj_set_style_text_color(ui_LBLmain, lv_color_hex(0xAD56C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LBLmain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LBLmain, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CTRstatus = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_CTRstatus);
    lv_obj_set_width(ui_CTRstatus, 256);
    lv_obj_set_height(ui_CTRstatus, 129);
    lv_obj_set_x(ui_CTRstatus, -132);
    lv_obj_set_y(ui_CTRstatus, 9);
    lv_obj_set_align(ui_CTRstatus, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CTRstatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LBLbroker = lv_label_create(ui_CTRstatus);
    lv_obj_set_width(ui_LBLbroker, 62);
    lv_obj_set_height(ui_LBLbroker, 16);
    lv_obj_set_x(ui_LBLbroker, -94);
    lv_obj_set_y(ui_LBLbroker, -27);
    lv_obj_set_align(ui_LBLbroker, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLbroker, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLbroker, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLbroker, "Broker:");

    ui_LBLwireless = lv_label_create(ui_CTRstatus);
    lv_obj_set_width(ui_LBLwireless, 72);
    lv_obj_set_height(ui_LBLwireless, 16);
    lv_obj_set_x(ui_LBLwireless, -89);
    lv_obj_set_y(ui_LBLwireless, -52);
    lv_obj_set_align(ui_LBLwireless, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLwireless, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLwireless, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLwireless, "Wireless:");

    ui_LBLpublish = lv_label_create(ui_CTRstatus);
    lv_obj_set_width(ui_LBLpublish, 66);
    lv_obj_set_height(ui_LBLpublish, 17);
    lv_obj_set_x(ui_LBLpublish, -91);
    lv_obj_set_y(ui_LBLpublish, 1);
    lv_obj_set_align(ui_LBLpublish, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLpublish, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLpublish, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLpublish, "Publish:");

    ui_LBLtopic = lv_label_create(ui_CTRstatus);
    lv_obj_set_width(ui_LBLtopic, 159);
    lv_obj_set_height(ui_LBLtopic, 12);
    lv_obj_set_x(ui_LBLtopic, 36);
    lv_obj_set_y(ui_LBLtopic, 1);
    lv_obj_set_align(ui_LBLtopic, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLtopic, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLtopic, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLtopic, "/test/topic/3");

    ui_LVLbrokerip = lv_label_create(ui_CTRstatus);
    lv_obj_set_width(ui_LVLbrokerip, 170);
    lv_obj_set_height(ui_LVLbrokerip, 15);
    lv_obj_set_x(ui_LVLbrokerip, 43);
    lv_obj_set_y(ui_LVLbrokerip, -25);
    lv_obj_set_align(ui_LVLbrokerip, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LVLbrokerip, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LVLbrokerip, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LVLbrokerip, "domain.test.com:1313");

    ui_LBLip = lv_label_create(ui_CTRstatus);
    lv_obj_set_width(ui_LBLip, 156);
    lv_obj_set_height(ui_LBLip, 15);
    lv_obj_set_x(ui_LBLip, 36);
    lv_obj_set_y(ui_LBLip, -52);
    lv_obj_set_align(ui_LBLip, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLip, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLip, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLip, "Connected");

    ui_CTRdata = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_CTRdata);
    lv_obj_set_width(ui_CTRdata, 256);
    lv_obj_set_height(ui_CTRdata, 129);
    lv_obj_set_x(ui_CTRdata, 127);
    lv_obj_set_y(ui_CTRdata, 10);
    lv_obj_set_align(ui_CTRdata, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CTRdata, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CTRdata, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CTRdata, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CTRdata, 55, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LBLpressure = lv_label_create(ui_CTRdata);
    lv_obj_set_width(ui_LBLpressure, 71);
    lv_obj_set_height(ui_LBLpressure, 16);
    lv_obj_set_x(ui_LBLpressure, -90);
    lv_obj_set_y(ui_LBLpressure, -28);
    lv_obj_set_align(ui_LBLpressure, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLpressure, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLpressure, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLpressure, "Pressure:");

    ui_LBLtemp = lv_label_create(ui_CTRdata);
    lv_obj_set_width(ui_LBLtemp, 72);
    lv_obj_set_height(ui_LBLtemp, 16);
    lv_obj_set_x(ui_LBLtemp, -87);
    lv_obj_set_y(ui_LBLtemp, -51);
    lv_obj_set_align(ui_LBLtemp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLtemp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLtemp, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLtemp, "Temp:");

    ui_LBLhumidity = lv_label_create(ui_CTRdata);
    lv_obj_set_width(ui_LBLhumidity, 76);
    lv_obj_set_height(ui_LBLhumidity, 17);
    lv_obj_set_x(ui_LBLhumidity, -88);
    lv_obj_set_y(ui_LBLhumidity, -5);
    lv_obj_set_align(ui_LBLhumidity, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLhumidity, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLhumidity, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLhumidity, "Humidity:");

    ui_LBLhumVAL = lv_label_create(ui_CTRdata);
    lv_obj_set_width(ui_LBLhumVAL, 159);
    lv_obj_set_height(ui_LBLhumVAL, 12);
    lv_obj_set_x(ui_LBLhumVAL, 42);
    lv_obj_set_y(ui_LBLhumVAL, -6);
    lv_obj_set_align(ui_LBLhumVAL, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLhumVAL, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLhumVAL, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLhumVAL, "11.1111123123");

    ui_LBLpressVAL = lv_label_create(ui_CTRdata);
    lv_obj_set_width(ui_LBLpressVAL, 170);
    lv_obj_set_height(ui_LBLpressVAL, 15);
    lv_obj_set_x(ui_LBLpressVAL, 46);
    lv_obj_set_y(ui_LBLpressVAL, -29);
    lv_obj_set_align(ui_LBLpressVAL, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLpressVAL, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLpressVAL, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLpressVAL, "123.12");

    ui_LBLtempVAL = lv_label_create(ui_CTRdata);
    lv_obj_set_width(ui_LBLtempVAL, 156);
    lv_obj_set_height(ui_LBLtempVAL, 15);
    lv_obj_set_x(ui_LBLtempVAL, 39);
    lv_obj_set_y(ui_LBLtempVAL, -52);
    lv_obj_set_align(ui_LBLtempVAL, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLtempVAL, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLtempVAL, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLtempVAL, "12.12346789");

    ui_LBLgas = lv_label_create(ui_CTRdata);
    lv_obj_set_width(ui_LBLgas, 76);
    lv_obj_set_height(ui_LBLgas, 17);
    lv_obj_set_x(ui_LBLgas, -86);
    lv_obj_set_y(ui_LBLgas, 18);
    lv_obj_set_align(ui_LBLgas, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLgas, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLgas, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLgas, "Gas:");

    ui_LBLaltitude = lv_label_create(ui_CTRdata);
    lv_obj_set_width(ui_LBLaltitude, 76);
    lv_obj_set_height(ui_LBLaltitude, 17);
    lv_obj_set_x(ui_LBLaltitude, -87);
    lv_obj_set_y(ui_LBLaltitude, 40);
    lv_obj_set_align(ui_LBLaltitude, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLaltitude, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLaltitude, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLaltitude, "Altitude:");

    ui_LBLgasVAL = lv_label_create(ui_CTRdata);
    lv_obj_set_width(ui_LBLgasVAL, 156);
    lv_obj_set_height(ui_LBLgasVAL, 15);
    lv_obj_set_x(ui_LBLgasVAL, 41);
    lv_obj_set_y(ui_LBLgasVAL, 18);
    lv_obj_set_align(ui_LBLgasVAL, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLgasVAL, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLgasVAL, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLgasVAL, "11.123");

    ui_LBLaltVAL = lv_label_create(ui_CTRdata);
    lv_obj_set_width(ui_LBLaltVAL, 156);
    lv_obj_set_height(ui_LBLaltVAL, 15);
    lv_obj_set_x(ui_LBLaltVAL, 42);
    lv_obj_set_y(ui_LBLaltVAL, 40);
    lv_obj_set_align(ui_LBLaltVAL, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LBLaltVAL, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LBLaltVAL, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LBLaltVAL, "121.1234678");

    uic_LBLmain = ui_LBLmain;
    uic_CTRstatus = ui_CTRstatus;
    uic_LBLbroker = ui_LBLbroker;
    uic_LBLwireless = ui_LBLwireless;
    uic_LBLpublish = ui_LBLpublish;
    uic_LBLtopic = ui_LBLtopic;
    uic_LVLbrokerip = ui_LVLbrokerip;
    uic_LBLip = ui_LBLip;
    uic_CTRdata = ui_CTRdata;
    uic_LBLpressure = ui_LBLpressure;
    uic_LBLtemp = ui_LBLtemp;
    uic_LBLhumidity = ui_LBLhumidity;
    uic_LBLhumVAL = ui_LBLhumVAL;
    uic_LBLpressVAL = ui_LBLpressVAL;
    uic_LBLtempVAL = ui_LBLtempVAL;
    uic_LBLgas = ui_LBLgas;
    uic_LBLaltitude = ui_LBLaltitude;
    uic_LBLgasVAL = ui_LBLgasVAL;
    uic_LBLaltVAL = ui_LBLaltVAL;

}
